Endoscopy Tool Tracking using VTK for HSDK 2.1 (#412)
* Update VTK sample with HSDK 2.1 support

Signed-off-by: Victor Chang <vicchang@nvidia.com>

* Support building with oeprators and additional args

Signed-off-by: Victor Chang <vicchang@nvidia.com>

* Set minimum version support to 1.0 and address review feedback

Signed-off-by: Victor Chang <vicchang@nvidia.com>

* Add copyright

Signed-off-by: Victor Chang <vicchang@nvidia.com>

---------

Signed-off-by: Victor Chang <vicchang@nvidia.com>

diff --git a/dev_container b/dev_container
--- a/dev_container
+++ b/dev_container
@@ -736,6 +736,8 @@ build_and_run_desc() { c_echo 'Build and run a requested application in a Docker
         --language : Specify the app language implementation to run.
                      Some applications provide both `cpp` and `python` implementations.
         --no_build : Launch the app without attempting to build it first
+        --build_args : Build the app with additional CMake configuration arguments
+        --build_with : List of optional operators that should be built separated by semicolons (;)
         --run_args : Run the app with additional args
         --verbose : Print extra output to console
         --dryrun : View build and run commands without doing anything
@@ -750,6 +752,8 @@ build_and_run() {
     local build_app=1
     local image_name=""
     local docker_file=""
+    local extra_build_args=""
+    local extra_build_with=""
     local extra_run_args=""
 
     # Parse CLI arguments next
@@ -788,6 +792,26 @@ build_and_run() {
             --no_build)
                 build_app=0
                 shift
+                ;;
+            --build_with)
+                if [[ -n "$2" ]]; then
+                    extra_build_with="--with '$2'"
+                    shift 2
+                else
+                    echo "Error: --build_with requires a value"
+                    build_and_run_desc
+                    exit 1
+                fi
+                ;;
+            --build_args)
+                if [[ -n "$2" ]]; then
+                    extra_build_args="--configure-args '$2'"
+                    shift 2
+                else
+                    echo "Error: --build_args requires a value"
+                    build_and_run_desc
+                    exit 1
+                fi
                 ;;
             --run_args)
                 if [[ -n "$2" ]]; then
@@ -851,7 +875,7 @@ build_and_run() {
 
     run_command ${SCRIPT_DIR}/dev_container build $container_build_args
     if [[ $build_app == 1 ]]; then
-        run_command ${SCRIPT_DIR}/dev_container launch $container_launch_args -- -c "./run build $app_name"
+        run_command ${SCRIPT_DIR}/dev_container launch $container_launch_args -- -c "./run build $app_name $extra_build_with $extra_build_args"
     fi
     run_command ${SCRIPT_DIR}/dev_container launch $container_launch_args -- -c "./run launch $app_name $app_language $extra_run_args"
 }
