custom nsys_location in dev_container
Signed-off-by: sohams <sohams@nvidia.com>

diff --git a/dev_container b/dev_container
--- a/dev_container
+++ b/dev_container
@@ -309,9 +309,6 @@ get_conditional_options() {
         # enable usage of the the perf_event_open call, see
         # https://docs.nvidia.com/nsight-systems/UserGuide/index.html#docker-profiling
         conditional_opt+="${prefix}--cap-add=SYS_ADMIN${postfix}"
-	if [[ "$gpu_type" == "igpu" ]]; then
-	    conditional_opt+="${prefix}-v /opt/nvidia/nsight-systems/2024.2.2:/opt/nvidia/nsight-systems/2024.2.2${postfix}"
-	fi
     fi
 
     # Allow X11 forwarding over SSH
@@ -599,6 +596,8 @@ Usage: ./dev_container launch [options]
     --local_sdk_root : Path to Holoscan SDK used for building local Holoscan SDK container
     --ssh_x11 : Enable X11 forwarding of graphical HoloHub applications over SSH
     --nsys_profile : Support Nsight Systems profiling in container
+    --nsys_location : (optional) Specify the location of the Nsight Systems installation on the host
+                       (e.g., /opt/nvidia/nsight-systems/2024.1.1/)
     --init : Support tini entry point
     --persistent : Does not delete container after it is run
     --verbose : Print variables passed to docker run command
@@ -619,6 +618,7 @@ launch() {
     local use_tini=0
     local persistent=0
     local nsys_profile=false
+    local nsys_location=""
     local as_root=false
     local docker_opts=""
 
@@ -671,6 +671,17 @@ launch() {
         --nsys_profile)
             nsys_profile=true
             shift
+            ;;
+        --nsys_location)
+            if [[ -n "$2" ]]; then
+                nsys_location="$2"
+                additional_volumes+="-v $nsys_location:/opt/nvidia/nsys-host "
+                shift 2
+            else
+                echo "Error: --nsys_location requires a value"
+                launch_desc
+                exit 1
+            fi
             ;;
         --as_root)
             as_root=true
@@ -778,11 +789,6 @@ launch() {
         user="root"
     else
         user="$(id -u):$(id -g)"
-    fi
-    if [[ "$gpu_type" == "igpu" ]] && [[ $nsys_profile == true ]]; then
-        # for iGPU, we need to install nsight in the host system
-	echo "Installing nsight on the host for iGPU container"
-	sudo apt update && sudo apt install -y nsight-systems-2024.2.2
     fi
 
     # DOCKER PARAMETERS
