Improve dev_container script (#355)
This patch adds invalid arguments handling logic to the `dev_container`
script and prints usage information on argument errors.

Signed-off-by: Arun Patole <apatole@nvidia.com>

diff --git a/dev_container b/dev_container
--- a/dev_container
+++ b/dev_container
@@ -282,6 +282,7 @@ get_compute_capacity() {
 }
 
 build_desc() { c_echo 'Build dev image
+Usage: ./dev_container build [options]
     --base_img : Fully qualified base image name, e.g. holoscan-sdk-dev:latest
     --docker_file :  path to Dockerfile to use for building container.
     --img : Specify fully qualified container name
@@ -308,23 +309,48 @@ build() {
     fi
 
     # Parse CLI arguments next
-    ARGS=("$@")
-    local i
-    local arg
-    for i in "${!ARGS[@]}"; do
-        arg="${ARGS[i]}"
-        if [ "$arg" = "--base_img" ]; then
-           base_img="${ARGS[i+1]}"
-        fi
-        if [ "$arg" = "--docker_file" ]; then
-           docker_file_path="${ARGS[i+1]}"
-        fi
-        if [ "$arg" = "--img" ]; then
-           img="${ARGS[i+1]}"
-        fi
-        if [ "$arg" = "--verbose" ]; then
-           print_verbose=1
-        fi
+    while [[ $# -gt 0 ]]; do
+        case "$1" in
+            --base_img)
+                if [[ -n "$2" && ! "$2" =~ ^-- ]]; then
+                    base_img="$2"
+                    shift 2
+                else
+                    echo "Error: --base_img requires a value"
+                    build_desc
+                    exit 1
+                fi
+                ;;
+            --docker_file)
+                if [[ -n "$2" && ! "$2" =~ ^-- ]]; then
+                    docker_file_path="$2"
+                    shift 2
+                else
+                    echo "Error: --docker_file requires a value"
+                    build_desc
+                    exit 1
+                fi
+                ;;
+            --img)
+                if [[ -n "$2" && ! "$2" =~ ^-- ]]; then
+                    img="$2"
+                    shift 2
+                else
+                    echo "Error: --img requires a value"
+                    build_desc
+                    exit 1
+                fi
+                ;;
+            --verbose)
+                print_verbose=1
+                shift
+                ;;
+            *)
+                echo "Error: Invalid argument '$1'"
+                build_desc
+                exit 1
+                ;;
+        esac
     done
 
     if [[ $print_verbose -gt 0 ]]; then
@@ -353,6 +379,7 @@ build() {
 #===============================================================================
 
 launch_desc() { c_echo 'Launch Docker container
+Usage: ./dev_container launch [options]
     --img   : Fully qualified image name, e.g.  holohub:sdk-local-latest-dgpu
     --local_sdk_root : Path to Holoscan SDK used for building local Holoscan SDK container
     --ssh_x11 : Enable X11 forwarding of graphical HoloHub applications over SSH
@@ -387,57 +414,80 @@ launch() {
     additional_volumes=""
 
     # Parse CLI arguments
-    ARGS=("$@")
-    local i
-    local arg
-    for i in "${!ARGS[@]}"; do
-        arg="${ARGS[i]}"
-        if [ "$arg" = "--img" ]; then
-           img="${ARGS[i+1]}"
-           shift
-           shift
-        fi
-        if [ "$arg" = "--verbose" ]; then
-           print_verbose=1
-           shift
-        fi
-        if [ "$arg" = "--local_sdk_root" ]; then
-           local_sdk_root="${ARGS[i+1]}"
-           shift
-           shift
-        fi
-        if [ "$arg" = "--ssh_x11" ]; then
-           ssh_x11=1
-           shift
-        fi
-        if [ "$arg" = "--init" ]; then
-           use_tini=1
-           shift
-        fi
-        if [ "$arg" = "--persistent" ]; then
-           persistent=1
-           shift
-        fi
-        if [ "$arg" = "--nsys_profile" ]; then
-           nsys_profile=true
-           shift
-        fi
-        if [ "$arg" = "--as_root" ]; then
-           as_root=true
-           shift
-        fi
-        if [ "$arg" = "--add-volume" ]; then
-            path="${ARGS[i+1]}"
-            base=$(basename "$path")
-            additional_volumes+="-v $path:/workspace/volumes/$base "
-            shift
-            shift
-        fi
-        if [ "$arg" = "--docker_opts" ]; then
-            docker_opts="${ARGS[i+1]}"
-            shift
-            shift
-        fi
+    while [[ $# -gt 0 ]]; do
+        case "$1" in
+            --img)
+                if [[ -n "$2" && ! "$2" =~ ^-- ]]; then
+                    img="$2"
+                    shift 2
+                else
+                    echo "Error: --img requires a value"
+                    launch_desc
+                    exit 1
+                fi
+                ;;
+            --verbose)
+                print_verbose=1
+                shift
+                ;;
+            --local_sdk_root)
+                if [[ -n "$2" && ! "$2" =~ ^-- ]]; then
+                    local_sdk_root="$2"
+                    shift 2
+                else
+                    echo "Error: --local_sdk_root requires a value"
+                    launch_desc
+                    exit 1
+                fi
+                ;;
+            --ssh_x11)
+                ssh_x11=1
+                shift
+                ;;
+            --init)
+                use_tini=1
+                shift
+                ;;
+            --persistent)
+                persistent=1
+                shift
+                ;;
+            --nsys_profile)
+                nsys_profile=true
+                shift
+                ;;
+            --as_root)
+                as_root=true
+                shift
+                ;;
+            --add-volume)
+                if [[ -n "$2" && ! "$2" =~ ^-- ]]; then
+                    path="$2"
+                    base=$(basename "$path")
+                    additional_volumes+="-v $path:/workspace/volumes/$base "
+                    shift 2
+                else
+                    echo "Error: --add-volume requires a value"
+                    launch_desc
+                    exit 1
+                fi
+                ;;
+            --docker_opts)
+                if [[ -n "$2" && ! "$2" =~ ^-- ]]; then
+                    docker_opts="$2"
+                    shift 2
+                else
+                    echo "Error: --docker_opts requires a value"
+                    launch_desc
+                    exit 1
+                fi
+                ;;
+            *)
+                echo "Error: Invalid argument '$1'"
+                launch_desc
+                exit 1
+                ;;
+        esac
     done
 
     # Check NVIDIA CTK version
@@ -689,37 +739,78 @@ build_and_run() {
     local extra_run_args=""
 
     # Parse CLI arguments next
-    ARGS=("$@")
-    local i
-    local arg
-    local skipnext=0
-    for i in "${!ARGS[@]}"; do
-        arg="${ARGS[i]}"
-        if [[ $skipnext == "1" ]]; then
-            skipnext=0
-        elif [ "$arg" = "--base_img" ]; then
-            container_build_args+=" --base_img ${ARGS[i+1]}"
-            skipnext=1
-        elif [ "$arg" = "--docker_file" ]; then
-            docker_file="${ARGS[i+1]}"
-            skipnext=1
-        elif [ "$arg" = "--img" ]; then
-            image_name="${ARGS[i+1]}"
-            skipnext=1
-        elif [ "$arg" = "--no_build" ]; then
-            build_app=0
-        elif [ "$arg" = "--run_args" ]; then
-            extra_run_args="--extra_args '${ARGS[i+1]}'"
-            skipnext=1
-        elif [ "$arg" = "--verbose" ]; then
-            container_build_args+=" --verbose"
-            container_launch_args+=" --verbose"
-        elif [ "$arg" = "--language" ]; then
-            app_language="${ARGS[i+1]}"
-            skipnext=1
-        elif [ -z "${app_name}" ]; then
-            app_name=$arg
-        fi
+    while [[ $# -gt 0 ]]; do
+        case "$1" in
+            --base_img)
+                if [[ -n "$2" && ! "$2" =~ ^-- ]]; then
+                    container_build_args+=" --base_img $2"
+                    shift 2
+                else
+                    echo "Error: --base_img requires a value"
+                    build_and_run_desc
+                    exit 1
+                fi
+                ;;
+            --docker_file)
+                if [[ -n "$2" && ! "$2" =~ ^-- ]]; then
+                    docker_file="$2"
+                    shift 2
+                else
+                    echo "Error: --docker_file requires a value"
+                    build_and_run_desc
+                    exit 1
+                fi
+                ;;
+            --img)
+                if [[ -n "$2" && ! "$2" =~ ^-- ]]; then
+                    image_name="$2"
+                    shift 2
+                else
+                    echo "Error: --img requires a value"
+                    build_and_run_desc
+                    exit 1
+                fi
+                ;;
+            --no_build)
+                build_app=0
+                shift
+                ;;
+            --run_args)
+                if [[ -n "$2" && ! "$2" =~ ^-- ]]; then
+                    extra_run_args="--extra_args '$2'"
+                    shift 2
+                else
+                    echo "Error: --run_args requires a value"
+                    build_and_run_desc
+                    exit 1
+                fi
+                ;;
+            --verbose)
+                container_build_args+=" --verbose"
+                container_launch_args+=" --verbose"
+                shift
+                ;;
+            --language)
+                if [[ -n "$2" && ! "$2" =~ ^-- ]]; then
+                    app_language="$2"
+                    shift 2
+                else
+                    echo "Error: --language requires a value"
+                    build_and_run_desc
+                    exit 1
+                fi
+                ;;
+            *)
+                if [[ -z "$app_name" ]]; then
+                    app_name="$1"
+                    shift
+                else
+                    echo "Error: Invalid argument '$1'"
+                    build_and_run_desc
+                    exit 1
+                fi
+                ;;
+        esac
     done
 
     if [ -z "${app_name}" ]; then
