dev_container: build_and_install command (#484)
* Add build_and_install and update build_and_run with container_args

Signed-off-by: Victor Chang <vicchang@nvidia.com>

* Update containerize section with build_and_install command

Signed-off-by: Victor Chang <vicchang@nvidia.com>

* Reuse build_and_run with two new options for build_and_install

Signed-off-by: Victor Chang <vicchang@nvidia.com>

* Update dev_container

Co-authored-by: Tom Birdsong <40648863+tbirdso@users.noreply.github.com>
Signed-off-by: Victor Chang <mocsharp@users.noreply.github.com>

---------

Signed-off-by: Victor Chang <vicchang@nvidia.com>
Signed-off-by: Victor Chang <mocsharp@users.noreply.github.com>
Co-authored-by: Tom Birdsong <40648863+tbirdso@users.noreply.github.com>

diff --git a/dev_container b/dev_container
--- a/dev_container
+++ b/dev_container
@@ -816,6 +816,16 @@ launch() {
         "$@"
 }
 
+build_and_install_desc() { c_echo 'Build the application and install the binaries into install/<app> if supported
+    Usage: ./dev_container build_and_install <application_name>
+    View options with `./dev_container build_and_run_desc`
+    '
+}
+
+build_and_install() {
+    build_and_run --install --no_run "$@"
+}
+
 build_and_run_desc() { c_echo 'Build and run a requested application in a Docker container
     Usage: ./dev_container build_and_run <application_name> [options]
     Options:
@@ -826,9 +836,12 @@ build_and_run_desc() { c_echo 'Build and run a requested application in a Docker
             - Otherwise the top-level HoloHub "Dockerfile"
             If `--img` is not specified then a custom image tag will be defined.
         --img : Specify fully qualified output container name
+        --container_args: Additional Docker run args.
         --language : Specify the app language implementation to run.
                      Some applications provide both `cpp` and `python` implementations.
         --no_build : Launch the app without attempting to build it first
+        --no_run : Skip launching the application.
+        --install: Install the application into install/<app> if supported.
         --build_args : Build the app with additional CMake configuration arguments
         --build_with : List of optional operators that should be built separated by semicolons (;)
         --run_args : Run the app with additional args
@@ -841,13 +854,16 @@ build_and_run() {
     local app_name=""
     local app_language=""
     local container_build_args=""
-    local container_launch_args="--docker_opts --entrypoint=bash"
+    local container_launch_args=""
+    local docker_opts="--entrypoint=bash"
     local build_app=1
     local image_name=""
     local docker_file=""
     local extra_build_args=""
     local extra_build_with=""
     local extra_run_args=""
+    local run_app=1
+    local install=""
 
     # Parse CLI arguments next
     while [[ $# -gt 0 ]]; do
@@ -926,6 +942,26 @@ build_and_run() {
                 exit 1
             fi
             ;;
+        --no_run)
+            if [[ -n "$2" ]]; then
+                run_app=0
+                shift 1
+            else
+                echo "Error: --run_args requires a value"
+                build_and_run_desc
+                exit 1
+            fi
+            ;;
+        --install)
+            if [[ -n "$2" ]]; then
+                install="--install"
+                shift 1
+            else
+                echo "Error: --run_args requires a value"
+                build_and_run_desc
+                exit 1
+            fi
+            ;;
         --verbose)
             container_build_args+=" --verbose"
             container_launch_args+=" --verbose"
@@ -937,6 +973,16 @@ build_and_run() {
                 shift 2
             else
                 echo "Error: --language requires a value"
+                build_and_run_desc
+                exit 1
+            fi
+            ;;
+        --container_args)
+            if [[ -n "$2" ]]; then
+                docker_opts+=" $2"
+                shift 2
+            else
+                echo "Error: --container_args requires a value"
                 build_and_run_desc
                 exit 1
             fi
@@ -976,11 +1022,17 @@ build_and_run() {
     container_build_args+=" --img $image_name"
     container_launch_args+=" --img $image_name"
 
+    c_echo "Building application container..."
     run_command ${SCRIPT_DIR}/dev_container build $container_build_args
     if [[ $build_app == 1 ]]; then
-        run_command ${SCRIPT_DIR}/dev_container launch $container_launch_args -- -c "./run build $app_name $extra_build_with $extra_build_args"
+        c_echo "Building application..."
+        run_command ${SCRIPT_DIR}/dev_container launch $container_launch_args --docker_opts "$docker_opts" -- -c "./run build $app_name $install $extra_build_with $extra_build_args"
     fi
-    run_command ${SCRIPT_DIR}/dev_container launch $container_launch_args -- -c "./run launch $app_name $app_language $extra_run_args"
+
+    if [[ $run_app == 1 ]]; then
+        c_echo "Launching application..."
+        run_command ${SCRIPT_DIR}/dev_container launch $container_launch_args --docker_opts "$docker_opts" -- -c "./run launch $app_name $app_language $extra_run_args"
+    fi
 }
 
 vscode_desc() { c_echo 'Launch VS Code in Dev Container
