Updated the dev_container script to check for the container toolkit version. Removed manual iGPU mappings and Vulkan ICD mappings which are now handled by the container toolkit.
Added docker settings needed for UCX (distributed apps).

Unconditionally add CUPY_CACHE_DIR define, this is not only needed
when using a local SDK path.

Signed-off-by: Andreas Heumann <aheumann@nvidia.com>

diff --git a/dev_container b/dev_container
--- a/dev_container
+++ b/dev_container
@@ -397,6 +397,25 @@ launch() {
         fi
     done
 
+    # Check NVIDIA CTK version
+    min_ctk_version="1.12.0"
+    recommended_ctk_version="1.14.1"
+    if ! command -v nvidia-ctk > /dev/null; then
+        fatal G "nvidia-ctk" W " not found. Please install the NVIDIA Container Toolkit."
+    fi
+    ctk_version_output=$(nvidia-ctk --version | grep version)
+    ctk_version_pattern="([0-9]+\.[0-9]+\.[0-9]+)"
+    if [[ "$ctk_version_output" =~ $ctk_version_pattern ]]; then
+        ctk_version="${BASH_REMATCH[1]}"
+        if [[ "$(echo -e "$ctk_version\n$min_ctk_version" | sort -V | head -n1)" == "$ctk_version" ]]; then
+            fatal "Found nvidia-ctk Version $ctk_version. Version $min_ctk_version+ is required ($recommended_ctk_version+ recommended)."
+        fi
+    else
+        c_echo_err R "Could not extract nvidia-ctk version number."
+        c_echo_err "  Version $min_ctk_version+ required."
+        c_echo_err "  Version $recommended_ctk_version+ recommended."
+    fi
+
     # Allow connecting from docker. This is not needed for WSL2 (`SI:localuser:wslg` is added by default)
     run_command xhost +local:docker
 
@@ -428,18 +447,6 @@ launch() {
     # add user in container to group video to access video devices, e.g. /dev/video0
     conditional_opt+=" --group-add video"
 
-    # if running on AGX Orin (iGPU only) or on IGX Orin in iGPU mode
-    if [[ $gpu_type == "igpu" ]] ; then
-        conditional_opt+=" --device /dev/nvgpu/igpu0/sched"
-        conditional_opt+=" --device /dev/nvgpu/igpu0/nvsched"
-        conditional_opt+=" --device /dev/nvhost-ctrl-nvdec"
-        conditional_opt+=" --device /dev/nvhost-ctxsw-gpu"
-        conditional_opt+=" --device /dev/nvhost-nvsched-gpu "
-        conditional_opt+=" --device /dev/nvhost-sched-gpu "
-        conditional_opt+=" --device /dev/nvidia0 "
-        conditional_opt+=" --device /dev/nvidia-modeset "
-    fi
-
     if [[ $nsys_profile == true ]] ; then
         # enable usage of the the perf_event_open call, see
         # https://docs.nvidia.com/nsight-systems/UserGuide/index.html#docker-profiling
@@ -456,16 +463,8 @@ launch() {
         local_sdk_opt+=" -e PYTHONPATH=/workspace/holoscan-sdk/build/python/lib"
         local_sdk_opt+=" -e HOLOSCAN_LIB_PATH=/workspace/holoscan-sdk/build/lib"
         local_sdk_opt+=" -e HOLOSCAN_SAMPLE_DATA_PATH=/workspace/holoscan-sdk/data"
-        #   Define path for cupy' kernel cache, needed since $HOME does
-        #   not exist when running with `-u id:group`
-        local_sdk_opt+=" -e CUPY_CACHE_DIR=/workspace/holoscan-sdk/.cupy/kernel_cache"
         local_sdk_opt+=" -e HOLOSCAN_TESTS_DATA_PATH=/workspace/holoscan-sdk/tests/data"
     fi
-
-
-    # Find the nvidia_icd.json file which could reside at different paths
-    # Needed due to https://github.com/NVIDIA/nvidia-container-toolkit/issues/16
-    nvidia_icd_json=$(find /usr/share /etc -path '*/vulkan/icd.d/nvidia_icd.json' -type f,l -print -quit 2>/dev/null | grep .) || (echo "nvidia_icd.json not found" >&2 && false)
 
     # Find the nvoptix.bin file
     if [ -f "/usr/share/nvidia/nvoptix.bin" ]; then
@@ -474,14 +473,23 @@ launch() {
 
     # Allow X11 forwarding over SSH
     if [[ $ssh_x11 -gt 0 ]]; then
-	XAUTH=/tmp/.docker.xauth
-	xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
-	chmod 777 $XAUTH
+        XAUTH=/tmp/.docker.xauth
+        xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
+        chmod 777 $XAUTH
 
-	conditional_opt+=" -v $XAUTH:$XAUTH"
-	conditional_opt+=" -e XAUTHORITY=$XAUTH"
+        conditional_opt+=" -v $XAUTH:$XAUTH"
+        conditional_opt+=" -e XAUTHORITY=$XAUTH"
     fi
 
+    # Define path for cupy's kernel cache, needed since $HOME does
+    # not exist when running with `-u id:group`
+    conditional_opt+=" -e CUPY_CACHE_DIR=/workspace/holohub/.cupy/kernel_cache"
+
+    # Options needed for UCX
+    ucx_opt=" --ipc=host"
+    ucx_opt+=" --cap-add=CAP_SYS_PTRACE"
+    ucx_opt+=" --ulimit memlock=-1"
+    ucx_opt+=" --ulimit stack=67108864"
 
     # DOCKER PARAMETERS
     #
@@ -511,12 +519,6 @@ launch() {
     # -e DISPLAY
     #   Enable graphical applications
     #
-    # -v $nvidia_icd_json:$nvidia_icd_json:ro
-    #   Bind NVIDIA's Vulkan installable client driver to run Vulkan
-    #   Needed due to https://github.com/NVIDIA/nvidia-container-toolkit/issues/16
-    #   The configurations files are installed to different locations when installing
-    #   with deb packages or with run files, so we look at both places
-    #
     # ${mount_nvoptix_bin}
     #   Mount Optix denoiser weights.
 
@@ -527,7 +529,7 @@ launch() {
         c_echo W "Launch (mount_device_opt: " G "${mount_device_opt}" W ")..."
         c_echo W "Launch (conditional_opt: " G "${conditional_opt}" W ")..."
         c_echo W "Launch (local_sdk_opt: " G "${local_sdk_opt}" W ")..."
-        c_echo W "Launch (nvidia_icd_json: " G "${nvidia_icd_json}" W ")..."
+        c_echo W "Launch (ucx_opt: " G "${ucx_opt}" W ")..."
         c_echo W "Launch (image: " G "${img}" W ")..."
     fi
 
@@ -545,8 +547,8 @@ launch() {
         ${mount_device_opt} \
     	${conditional_opt} \
         ${local_sdk_opt} \
-        -v $nvidia_icd_json:$nvidia_icd_json:ro \
         ${mount_nvoptix_bin} \
+        ${ucx_opt} \
         ${img} \
         "$@"
 }
