IsaacSim Holoscan bridge

diff --git a/dev_container b/dev_container
--- a/dev_container
+++ b/dev_container
@@ -925,6 +925,7 @@ build_and_run_desc() { c_echo 'Build and run a requested application in a Docker
             If `--img` is not specified then a custom image tag will be defined.
         --img : Specify fully qualified output container name
         --container_args: Additional Docker run args.
+        --container_launch_args: Additional Docker launch args.
         --language : Specify the app language implementation to run.
                      Some applications provide both `cpp` and `python` implementations.
         --no_build : Launch the app without attempting to build it first
@@ -1064,6 +1065,16 @@ build_and_run() {
                 shift 2
             else
                 echo "Error: --language requires a value"
+                build_and_run_desc
+                exit 1
+            fi
+            ;;
+        --container_launch_args)
+            if [[ -n "$2" ]]; then
+                container_launch_args+="$2"
+                shift 2
+            else
+                echo "Error: --container_launch_args requires a value"
                 build_and_run_desc
                 exit 1
             fi
