Add linting to run script (#14)
* Add linting to run script
* Lint fixes

diff --git a/run b/run
--- a/run
+++ b/run
@@ -15,6 +15,10 @@
 # limitations under the License.
 
 SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
+HOLOHUB_PY_EXE=${HOLOHUB_PY_EXE:-"python3"}
+
+#===========================================================================================
+# Utilities
 
 # Compare versions
 compare_version () {
@@ -55,7 +59,23 @@ compare_version () {
     return 0
 }
 
+
+run_command() {
+    local status=0
+    local cmd="$*"
+
+    [ "$(echo -n "$@")" = "" ] && return 1 # return 1 if there is no command available
+
+    "$@"
+    status=$?
+
+    return $status
+}
+
+
+#===========================================================================================
 # Helper function to install packages
+
 install_cuda_dependencies_package() {
    package_name=$1
    preferred_version=$2
@@ -182,7 +202,105 @@ setup() {
   echo "Setup for HoloHub is ready. Happy Holocoding!"
 }
 
+#===========================================================================================
+# Lint
+
+install_lint_deps_desc() { echo 'Install lint dependencies
+
+This command will install the dependencies required to run the linting tools.
+
+- Python linting: ruff, isort, black, mypy
+- C++ linting: cpplint
+- Spelling: codespell
+'
+}
+install_lint_deps() {
+    # We use $(command) || exit_code=1 to run all linting tools, and exit
+    # with failure after all commands were executed if any of them failed
+    local exit_code=0
+
+    pushd ${SCRIPT_DIR} > /dev/null
+
+    echo "Install Lint Dependencies for Python"
+    if ! command -v ruff &> /dev/null; then
+        run_command ${HOLOHUB_PY_EXE} -m pip install ruff || exit_code=1
+    fi
+    if ! command -v isort &> /dev/null; then
+        run_command ${HOLOHUB_PY_EXE} -m pip install isort || exit_code=1
+    fi
+    if ! command -v black &> /dev/null; then
+        run_command ${HOLOHUB_PY_EXE} -m pip install black || exit_code=1
+    fi
+    if ! command -v mypy &> /dev/null; then
+        run_command ${HOLOHUB_PY_EXE} -m pip install mypy || exit_code=1
+    fi
+
+    echo "Install Lint Dependencies for C++"
+    if ! command -v cpplint &> /dev/null; then
+        run_command ${HOLOHUB_PY_EXE} -m pip install cpplint || exit_code=1
+    fi
+
+    echo "Install Lint Dependencies for Code Spelling"
+    if ! command -v codespell &> /dev/null; then
+        run_command ${HOLOHUB_PY_EXE} -m pip install codespell || exit_code=1
+    fi
+
+    popd > /dev/null
+
+    exit $exit_code
+}
+
+lint_desc() { echo 'Lint the repository
+
+Python linting: black, isort, ruff
+C++ linting: cpplint
+Spelling: codespell
+
+Arguments:
+  $@ - directories to lint (default: .)
+'
+}
+
+lint() {
+    local DIR_TO_RUN=${@:-"."}
+
+    # We use $(command) || exit_code=1 to run all linting tools, and exit
+    # with failure after all commands were executed if any of them failed
+    local exit_code=0
+
+    pushd ${SCRIPT_DIR} > /dev/null
+
+    echo "Linting Python"
+    run_command ruff $DIR_TO_RUN || exit_code=1
+    run_command ${HOLOHUB_PY_EXE} -m isort -c $DIR_TO_RUN || exit_code=1
+    run_command ${HOLOHUB_PY_EXE} -m black --check $DIR_TO_RUN || exit_code=1
+
+    echo "Linting C++"
+    # We use `grep -v` to hide verbose output that drowns actual errors
+    # Since we care about the success/failure of cpplitn and not of grep, we:
+    #  1. use `set -o pipefail` to fail if `cpplint` fails
+    #  2. use `grep -v ... || true` to ignore whether grep hid any output
+    run_command set -o pipefail; ${HOLOHUB_PY_EXE} -m cpplint \
+            --exclude build \
+            --exclude install \
+            --exclude build-\* \
+            --exclude install-\* \
+            --recursive $DIR_TO_RUN \
+        | { grep -v "Ignoring\|Done processing" || true; } || exit_code=1
+
+
+    echo "Code spelling"
+    run_command codespell $DIR_TO_RUN --skip="*.onnx" || exit_code=1
+
+    popd > /dev/null
+
+    exit $exit_code
+}
+
+
+#===========================================================================================
 # Build HoloHub sample apps
+
 build_desc() {
   echo ""
   echo "Build the application(s) in HoloHub"
@@ -339,16 +457,16 @@ for k, v in obj["application"]["run"].items():
 ')
 
    local json_command=$(echo $json | grep -Po 'command="\K[^"]*')
-   local run_command=$json_command
+   local command=$json_command
 
    # replace <holohub_data_dir> by the data dir
-   local run_command=$(echo "${json_command//<holohub_data_dir>/$holohub_data_dir}")
+   local command=$(echo "${json_command//<holohub_data_dir>/$holohub_data_dir}")
 
    # replace <holohub_app_bin> by the binary app directory
-   run_command=$(echo "${run_command//<holohub_app_bin>/$holohub_app_bin}")
+   command=$(echo "${command//<holohub_app_bin>/$holohub_app_bin}")
 
    # replace <holohub_app_source> by the source app directory
-   run_command=$(echo "${run_command//<holohub_app_source>/$holohub_app_source}")
+   command=$(echo "${command//<holohub_app_source>/$holohub_app_source}")
 
    # default workdir is bin
    local workdir="cd ${holohub_app_bin}"
@@ -362,10 +480,10 @@ for k, v in obj["application"]["run"].items():
    local environment="export PYTHONPATH=${holoscan_sdk_install}/../../../python/lib:${holohub_buildir}/python/lib"
 
    echo "workdir=${workdir}"
-   echo "command=${run_command}"
+   echo "command=${command}"
 
    # Run the command
-   $environment && $workdir && $run_command
+   $environment && $workdir && $command
 }
 
 
